import React,{createContext,useContext,useEffect,useMemo,useState} from 'react';
import {AppAlert,CancellationReason,Complaint,Message,Provider,ProviderAccountStatus,ProviderAvailability,Request,RequestInput,Review,Role,Service,ServicePricing,SystemSettings,UserProfile} from '../types';
import {availabilityRowsToRecord,firebaseLogin,firebaseLoginWithGoogleIdToken,firebaseLoginWithGooglePopup,firebaseLogout,firebaseRepository,firebaseSendPasswordReset,isFirebaseConfigured,onFirebaseAuthChanged,statusRowsToRecord} from '../services/firebase';
import {distanceInKm,getCurrentLocation} from '../services/location';

type CompletionProofInput={notes:string;photos:string[]};
type AlertInput=Omit<AppAlert,'id'|'createdAt'|'read'> & {read?:boolean};
type MessageMeta={requestId?:string;title?:string;avatar?:string;recipientRoles?:Role[]};
type Context={role:Role;authenticated:boolean;login:(email:string,password:string)=>Promise<boolean>;loginWithGooglePopup:()=>Promise<boolean>;loginWithGoogleIdToken:(idToken:string)=>Promise<boolean>;resetPassword:(email:string)=>Promise<boolean>;logout:()=>void;requests:Request[];addRequest:(r:Request)=>void;createRequest:(r:RequestInput)=>Request;updateRequest:(id:string,status:Request['status'])=>void;verifyArrival:(id:string)=>Promise<boolean>;submitCompletionProof:(id:string,proof:CompletionProofInput)=>boolean;submitQuote:(id:string,pricing:Omit<ServicePricing,'total'|'platformFee'|'providerEarnings'>)=>boolean;approveQuote:(id:string)=>boolean;rejectQuote:(id:string)=>boolean;canCancelRequest:(request:Request)=>boolean;cancelRequest:(id:string,reason?:CancellationReason)=>boolean;removeRequest:(id:string)=>void;favourites:string[];toggleFavourite:(id:string)=>void;messages:Message[];sendMessage:(providerId:string,text:string,meta?:MessageMeta)=>void;markMessageRead:(id:string)=>void;alerts:AppAlert[];pushAlert:(alert:AlertInput)=>void;markAlertRead:(id:string)=>void;markAllAlertsRead:()=>void;reviews:Review[];addReview:(review:Review)=>void;hasReview:(requestId:string)=>boolean;complaints:Complaint[];addComplaint:(complaint:Complaint)=>void;providerDirectory:Provider[];addProvider:(provider:Provider)=>void;serviceDirectory:Service[];addService:(service:Service)=>void;providerStatuses:Record<string,ProviderAccountStatus>;setProviderStatus:(id:string,status:ProviderAccountStatus)=>void;availability:ProviderAvailability;setAvailability:(id:string,value:boolean)=>void;systemSettings:SystemSettings;setMaintenanceMode:(value:boolean)=>void;profile:UserProfile;updateProfile:(patch:Partial<UserProfile>)=>void;ready:boolean;firebaseReady:boolean};

const noop=()=>{};
const emptyProfile:UserProfile={name:'',email:'',phone:'',address:'',notifications:true,role:'customer',favourites:[],paymentMethods:[]};
const defaultSystemSettings:SystemSettings={id:'platform',maintenance:false};
const AppContext=createContext<Context>({role:'customer',authenticated:false,login:async()=>false,loginWithGooglePopup:async()=>false,loginWithGoogleIdToken:async()=>false,resetPassword:async()=>false,logout:noop,requests:[],addRequest:noop,createRequest:(r)=>({...r,id:'',status:r.status||'Pending'} as Request),updateRequest:noop,verifyArrival:async()=>false,submitCompletionProof:()=>false,submitQuote:()=>false,approveQuote:()=>false,rejectQuote:()=>false,canCancelRequest:()=>false,cancelRequest:()=>false,removeRequest:noop,favourites:[],toggleFavourite:noop,messages:[],sendMessage:noop,markMessageRead:noop,alerts:[],pushAlert:noop,markAlertRead:noop,markAllAlertsRead:noop,reviews:[],addReview:noop,hasReview:()=>false,complaints:[],addComplaint:noop,providerDirectory:[],addProvider:noop,serviceDirectory:[],addService:noop,providerStatuses:{},setProviderStatus:noop,availability:{},setAvailability:noop,systemSettings:defaultSystemSettings,setMaintenanceMode:noop,profile:emptyProfile,updateProfile:noop,ready:false,firebaseReady:isFirebaseConfigured});

const allowedTransitions:Record<Request['status'],Request['status'][]>={Searching:['Pending','Cancelled'],Pending:['Accepted','Cancelled'],Accepted:['Arrived','Cancelled'],Arrived:['In progress','Cancelled'],['In progress']:['Completed','Cancelled'],Completed:[],Cancelled:[]};
const persist=<T,>(work:Promise<T>)=>work.catch(error=>console.warn('Firebase write failed',error));

export function AppProvider({children}:{children:React.ReactNode}){
 const [role,setRoleState]=useState<Role>('customer');
 const [requests,setRequests]=useState<Request[]>([]);
 const [favourites,setFavourites]=useState<string[]>([]);
 const [messages,setMessages]=useState<Message[]>([]);
 const [alerts,setAlerts]=useState<AppAlert[]>([]);
 const [reviews,setReviews]=useState<Review[]>([]);
 const [complaints,setComplaints]=useState<Complaint[]>([]);
 const [providerDirectory,setProviderDirectory]=useState<Provider[]>([]);
 const [serviceDirectory,setServiceDirectory]=useState<Service[]>([]);
 const [providerStatuses,setProviderStatuses]=useState<Record<string,ProviderAccountStatus>>({});
 const [availability,setAvailabilityState]=useState<ProviderAvailability>({});
 const [systemSettings,setSystemSettingsState]=useState<SystemSettings>(defaultSystemSettings);
 const [profile,setProfile]=useState<UserProfile>(emptyProfile);
 const [ready,setReady]=useState(false);
 const [authenticated,setAuthenticated]=useState(false);
 const [firebaseUid,setFirebaseUid]=useState('');

 useEffect(()=>{if(!isFirebaseConfigured){setReady(true);return;}let mounted=true;firebaseRepository.providers.list().then(v=>mounted&&setProviderDirectory(v)).catch(()=>{});firebaseRepository.services.list().then(v=>mounted&&setServiceDirectory(v)).catch(()=>{});const unsubscribe=onFirebaseAuthChanged(async user=>{if(!mounted)return;if(!user){setAuthenticated(false);setFirebaseUid('');setProfile(emptyProfile);setRoleState('customer');setRequests([]);setMessages([]);setAlerts([]);setReviews([]);setComplaints([]);setProviderStatuses({});setAvailabilityState({});setSystemSettingsState(defaultSystemSettings);setFavourites([]);setReady(true);return;}setAuthenticated(true);setFirebaseUid(user.uid);let storedProfile=await firebaseRepository.profiles.get(user.uid).catch(()=>null);if(!storedProfile){storedProfile={...emptyProfile,id:user.uid,email:user.email||'',name:user.displayName||user.email?.split('@')[0]||'One-day local services user',role:'customer'};await firebaseRepository.profiles.upsert(storedProfile).catch(error=>console.warn('Firebase profile create failed',error));}storedProfile={...emptyProfile,...storedProfile};const [r,m,n,v,c,providers,services,statusRows,availabilityRows,settings]=await Promise.all([firebaseRepository.requests.list().catch(()=>[]),firebaseRepository.messages.list().catch(()=>[]),firebaseRepository.alerts.list().catch(()=>[]),firebaseRepository.reviews.list().catch(()=>[]),firebaseRepository.complaints.list().catch(()=>[]),firebaseRepository.providers.list().catch(()=>[]),firebaseRepository.services.list().catch(()=>[]),firebaseRepository.providerStatuses.list().catch(()=>[]),firebaseRepository.availability.list().catch(()=>[]),firebaseRepository.systemSettings.get('platform').catch(()=>null)]);if(!mounted)return;setProfile(storedProfile);setFavourites(storedProfile.favourites||[]);setRoleState(storedProfile.role);setRequests(r);setMessages(m);setAlerts(n);setReviews(v);setComplaints(c);setProviderDirectory(providers);setServiceDirectory(services);setProviderStatuses(statusRowsToRecord(statusRows));setAvailabilityState(availabilityRowsToRecord(availabilityRows));setSystemSettingsState(settings||defaultSystemSettings);setReady(true);});return()=>{mounted=false;unsubscribe();};},[]);

 const login=async(email:string,password:string)=>{if(!isFirebaseConfigured)return false;try{await firebaseLogin(email.trim(),password);return true;}catch(error){console.warn('Firebase login failed',error);return false;}};
 const loginWithGooglePopup=async()=>{if(!isFirebaseConfigured)return false;try{await firebaseLoginWithGooglePopup();return true;}catch(error){console.warn('Firebase Google popup login failed',error);return false;}};
 const loginWithGoogleIdToken=async(idToken:string)=>{if(!isFirebaseConfigured||!idToken)return false;try{await firebaseLoginWithGoogleIdToken(idToken);return true;}catch(error){console.warn('Firebase Google token login failed',error);return false;}};
 const resetPassword=async(email:string)=>{if(!isFirebaseConfigured||!email.trim())return false;try{await firebaseSendPasswordReset(email.trim());return true;}catch(error){console.warn('Firebase password reset failed',error);return false;}};
 const logout=()=>{firebaseLogout().catch(()=>{});setAuthenticated(false);};
 const updateProfile=(patch:Partial<UserProfile>)=>{const {role:ignoredRole,...safePatch}=patch;void ignoredRole;const next={...profile,...safePatch,role};setProfile(next);if(safePatch.favourites)setFavourites(safePatch.favourites);if(firebaseUid)persist(firebaseRepository.profiles.upsert({...next,id:firebaseUid}));};

 const pushAlert=(alert:AlertInput)=>{const item:AppAlert={...alert,id:`alert_${Date.now()}_${alerts.length}`,createdAt:new Date().toISOString(),read:alert.read||false};setAlerts(current=>[item,...current].slice(0,80));persist(firebaseRepository.alerts.upsert(item));};
 const markAlertRead=(id:string)=>{setAlerts(current=>current.map(alert=>alert.id===id?{...alert,read:true}:alert));const target=alerts.find(alert=>alert.id===id);if(target)persist(firebaseRepository.alerts.upsert({...target,read:true}));};
 const markAllAlertsRead=()=>setAlerts(current=>current.map(alert=>{if(!alert.recipientRoles.includes(role))return alert;const next={...alert,read:true};persist(firebaseRepository.alerts.upsert(next));return next;}));
 const notify=(recipientRoles:Role[],title:string,text:string,type:AppAlert['type']='system',requestId?:string)=>pushAlert({recipientRoles,title,text,type,requestId});

 const addRequest=(request:Request)=>{const item={...request,createdAt:request.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),paymentStatus:request.paymentStatus||'unpaid',arrivalStatus:request.arrivalStatus||'not_started',providerDistanceKm:request.providerDistanceKm??2.4};setRequests(current=>[item,...current]);persist(firebaseRepository.requests.upsert(item));notify(['provider','administrator','system-admin'],'New job request',`${item.customer||'A customer'} requested ${item.service}.`,'booking',item.id);};
 const createRequest=(input:RequestInput)=>{const now=new Date().toISOString();const request={...input,id:`req_${Date.now()}`,status:input.status||'Searching',createdAt:now,updatedAt:now,paymentStatus:input.paymentStatus||'unpaid',arrivalStatus:input.arrivalStatus||'not_started',providerDistanceKm:input.providerDistanceKm??2.4} as Request;addRequest(request);return request;};
 const saveRequest=(item:Request)=>{setRequests(current=>current.map(request=>request.id===item.id?item:request));persist(firebaseRepository.requests.upsert(item));};
 const updateRequest=(id:string,status:Request['status'])=>{const request=requests.find(item=>item.id===id);if(!request)return;const allowed=allowedTransitions[request.status].includes(status);const arrivalRequired=request.status==='Accepted'&&status==='Arrived'&&request.quoteStatus!=='approved';const startRequired=request.status==='Arrived'&&status==='In progress'&&request.arrivalStatus!=='arrived';const quoteRequired=request.status==='In progress'&&status==='Completed'&&request.quoteStatus!=='approved';const proofRequired=request.status==='In progress'&&status==='Completed'&&request.completionProofStatus!=='submitted'&&request.completionProofStatus!=='accepted';if(!allowed||arrivalRequired||startRequired||quoteRequired||proofRequired)return;saveRequest({...request,status,completionProofStatus:status==='Completed'?'accepted':request.completionProofStatus,completedAt:status==='Completed'?new Date().toISOString():request.completedAt,paymentStatus:status==='Completed'&&request.quoteStatus==='approved'?'paid':request.paymentStatus,updatedAt:new Date().toISOString()});};
 const verifyArrival=async(id:string)=>{const target=requests.find(request=>request.id===id);if(!target||target.status!=='Accepted'||target.quoteStatus!=='approved')return false;const providerLocation=await getCurrentLocation();if(!providerLocation||!target.serviceCoordinates){saveRequest({...target,arrivalStatus:'manual_review',updatedAt:new Date().toISOString()});return false;}const distanceMeters=Math.round((distanceInKm(providerLocation,target.serviceCoordinates)??999)*1000);if(distanceMeters>100){saveRequest({...target,arrivalStatus:'manual_review',arrivalDistanceMeters:distanceMeters,providerDistanceKm:Number((distanceMeters/1000).toFixed(1)),updatedAt:new Date().toISOString()});return false;}const item={...target,status:'Arrived' as const,arrivalStatus:'arrived' as const,arrivedAt:new Date().toISOString(),arrivalDistanceMeters:distanceMeters,providerDistanceKm:Number((distanceMeters/1000).toFixed(1)),estimatedArrivalMinutes:0,updatedAt:new Date().toISOString()};saveRequest(item);notify(['customer'],'Provider arrived',`${target.provider} has arrived for ${target.service}.`,'arrival',id);return true;};
 const submitCompletionProof=(id:string,proof:CompletionProofInput)=>{const notes=proof.notes.trim();const photos=proof.photos.filter(Boolean);const target=requests.find(request=>request.id===id);if(!notes||photos.length===0||!target||target.status!=='In progress'||target.quoteStatus!=='approved')return false;const now=new Date().toISOString();saveRequest({...target,status:'Completed',completionNotes:notes,completionPhotos:photos,completionProofStatus:'submitted',completedAt:now,paymentStatus:'paid',updatedAt:now});notify(['customer','administrator'],'Job completed',`${target.provider} submitted completion proof for ${target.service}.`,'payment',id);return true;};
 const submitQuote=(id:string,input:Omit<ServicePricing,'total'|'platformFee'|'providerEarnings'>)=>{const target=requests.find(request=>request.id===id);if(!target||!['Pending','Accepted','In progress'].includes(target.status))return false;const billingModel=input.billingModel||'hourly';const billableHours=billingModel==='hourly'?Math.max(input.labourHours||0,input.minimumHours||1):input.labourHours||1;const labour=billingModel==='hourly'?Math.round((input.labourRate||0)*billableHours):input.labour;const total=input.callOut+labour+input.materials+input.extras;const platformFee=Math.round(total*.15);const pricing={...input,billingModel,labour,billableHours,total,platformFee,providerEarnings:total-platformFee,submittedAt:new Date().toISOString()};saveRequest({...target,pricing,quoteStatus:'pending_approval',paymentStatus:'unpaid',updatedAt:new Date().toISOString()});notify(['customer'],'Quote received',`${target.provider} sent a quote for ${target.service}: R${total}.`,'quote',id);return true;};
 const approveQuote=(id:string)=>{const target=requests.find(request=>request.id===id);if(!target||target.quoteStatus!=='pending_approval'||!target.pricing)return false;saveRequest({...target,status:target.status==='Pending'?'Accepted':target.status,quoteStatus:'approved',paymentStatus:'authorised',arrivalStatus:'en_route',providerDistanceKm:target.providerDistanceKm??2.4,pricing:{...target.pricing,approvedAt:new Date().toISOString()},price:`R${target.pricing.total}`,updatedAt:new Date().toISOString()});notify(['provider','administrator'],'Quote accepted',`${target.customer||'Customer'} accepted the ${target.service} quote.`,'quote',id);return true;};
 const rejectQuote=(id:string)=>{const target=requests.find(request=>request.id===id);if(!target||target.quoteStatus!=='pending_approval')return false;saveRequest({...target,quoteStatus:'rejected',paymentStatus:'unpaid',updatedAt:new Date().toISOString()});notify(['provider'],'Quote declined',`${target.customer||'Customer'} declined the ${target.service} quote.`,'quote',id);return true;};
 const cancellableStatuses:Request['status'][]=['Searching','Pending','Accepted'];
 const canCancelRequest=(request:Request)=>cancellableStatuses.includes(request.status)&&(role==='customer'||role==='provider'||role==='administrator'||role==='system-admin');
 const cancelRequest=(id:string,reason:CancellationReason='Other')=>{const target=requests.find(request=>request.id===id);if(!target||!canCancelRequest(target))return false;const fee=role==='customer'&&target.status==='Accepted'?'R50':'R0';saveRequest({...target,status:'Cancelled',cancelledAt:new Date().toISOString(),cancellationReason:reason,cancellationFee:fee,updatedAt:new Date().toISOString()});notify(['customer','provider','administrator'],`Booking cancelled`,`${target.service} was cancelled. Reason: ${reason}.`,'booking',id);return true;};
 const removeRequest=(id:string)=>{setRequests(current=>current.filter(request=>request.id!==id));persist(firebaseRepository.requests.remove(id));};

 const sendMessage=(providerId:string,text:string,meta?:MessageMeta)=>{const provider=providerDirectory.find(item=>item.id===providerId);const recipientRoles=meta?.recipientRoles|| (role==='customer'?['provider'] as Role[]:role==='provider'?['customer'] as Role[]:role==='administrator'?['customer','provider'] as Role[]:['administrator'] as Role[]);const title=meta?.title||provider?.name||'One-day local services conversation';const avatar=meta?.avatar||provider?.avatar||title.split(' ').map(x=>x[0]).join('').slice(0,2)||'1D';const existing=messages.find(m=>(meta?.requestId&&m.requestId===meta.requestId)||m.providerId===providerId);const item:Message={providerId,provider:title,avatar,text,timestamp:'now',unread:true,requestId:meta?.requestId,senderRole:role,senderName:profile.name,recipientRoles,unreadFor:recipientRoles,id:existing?.id||`msg_${Date.now()}`};setMessages(x=>existing?[item,...x.filter(m=>m.id!==existing.id)]:[item,...x]);persist(firebaseRepository.messages.upsert(item));notify(recipientRoles,'New message',`${profile.name}: ${text}`,'message',meta?.requestId);};
 const markMessageRead=(id:string)=>{const target=messages.find(m=>m.id===id);setMessages(x=>x.map(m=>m.id===id?{...m,unread:false,unreadFor:(m.unreadFor||[]).filter(item=>item!==role)}:m));if(target)persist(firebaseRepository.messages.upsert({...target,unread:false,unreadFor:(target.unreadFor||[]).filter(item=>item!==role)}));};

 const addReview=(review:Review)=>{setReviews(x=>x.some(existing=>existing.requestId===review.requestId)?x:[review,...x]);persist(firebaseRepository.reviews.upsert(review));};
 const hasReview=(requestId:string)=>reviews.some(r=>r.requestId===requestId);
 const addComplaint=(complaint:Complaint)=>{setComplaints(x=>[complaint,...x]);persist(firebaseRepository.complaints.upsert(complaint));notify(['administrator','system-admin'],'New complaint',`${complaint.customer}: ${complaint.subject}`,'complaint',complaint.requestId);};
 const addProvider=(provider:Provider)=>{setProviderDirectory(x=>[...x,provider]);persist(firebaseRepository.providers.upsert(provider));};
 const addService=(service:Service)=>{setServiceDirectory(x=>[...x,service]);persist(firebaseRepository.services.upsert(service));};
 const setProviderStatus=(id:string,status:ProviderAccountStatus)=>{setProviderStatuses(x=>({...x,[id]:status}));persist(firebaseRepository.providerStatuses.upsert({id,status}));notify(['administrator','system-admin'],'Provider status changed',`${id} is now ${status}.`,'system');};
 const setAvailability=(id:string,value:boolean)=>{setAvailabilityState(x=>({...x,[id]:value}));persist(firebaseRepository.availability.upsert({id,available:value}));};
 const setMaintenanceMode=(value:boolean)=>{const next={...systemSettings,id:'platform',maintenance:value};setSystemSettingsState(next);persist(firebaseRepository.systemSettings.upsert(next));};
 const toggleFavourite=(id:string)=>setFavourites(current=>{const next=current.includes(id)?current.filter(i=>i!==id):[...current,id];const nextProfile={...profile,favourites:next,role};setProfile(nextProfile);if(firebaseUid)persist(firebaseRepository.profiles.upsert({...nextProfile,id:firebaseUid}));return next;});

 const value=useMemo<Context>(()=>({role,authenticated,login,loginWithGooglePopup,loginWithGoogleIdToken,resetPassword,logout,requests,addRequest,createRequest,updateRequest,verifyArrival,submitCompletionProof,submitQuote,approveQuote,rejectQuote,canCancelRequest,cancelRequest,removeRequest,favourites,toggleFavourite,messages,sendMessage,markMessageRead,alerts,pushAlert,markAlertRead,markAllAlertsRead,reviews,addReview,hasReview,complaints,addComplaint,providerDirectory,addProvider,serviceDirectory,addService,providerStatuses,setProviderStatus,availability,setAvailability,systemSettings,setMaintenanceMode,profile,updateProfile,ready,firebaseReady:isFirebaseConfigured}),[role,authenticated,requests,favourites,messages,alerts,reviews,complaints,providerDirectory,serviceDirectory,providerStatuses,availability,systemSettings,profile,ready]);
 return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export const useApp=()=>useContext(AppContext);
