import React,{createContext,useContext,useEffect,useMemo,useState} from 'react';
import {initialRequests} from '../data/mockData';
import {Message,ProviderAccountStatus,ProviderAvailability,Request,Review,Role,UserProfile} from '../types';
import {loadAvailability,loadFavourites,loadMessages,loadProfile,loadProviderStatuses,loadRequests,loadReviews,saveAvailability,saveFavourites,saveMessages,saveProfile,saveProviderStatuses,saveRequests,saveReviews} from '../services/storage';
type Context={role:Role;setRole:(role:Role)=>void;requests:Request[];addRequest:(r:Request)=>void;updateRequest:(id:string,status:Request['status'])=>void;removeRequest:(id:string)=>void;favourites:string[];toggleFavourite:(id:string)=>void;messages:Message[];sendMessage:(providerId:string,text:string)=>void;markMessageRead:(id:string)=>void;reviews:Review[];addReview:(review:Review)=>void;providerStatuses:Record<string,ProviderAccountStatus>;setProviderStatus:(id:string,status:ProviderAccountStatus)=>void;availability:ProviderAvailability;setAvailability:(id:string,value:boolean)=>void;profile:UserProfile;updateProfile:(patch:Partial<UserProfile>)=>void;ready:boolean};
const noop=()=>{};
const AppContext=createContext<Context>({role:'customer',setRole:noop,requests:[],addRequest:noop,updateRequest:noop,removeRequest:noop,favourites:[],toggleFavourite:noop,messages:[],sendMessage:noop,markMessageRead:noop,reviews:[],addReview:noop,providerStatuses:{},setProviderStatus:noop,availability:{},setAvailability:noop,profile:{name:'Alex Morgan',email:'alex@example.com',phone:'',address:'12 Long Street, Cape Town',notifications:true,role:'customer'},updateProfile:noop,ready:false});
const defaultMessages:Message[]=[{id:'m1',providerId:'p1',provider:'Thabo Mokoena',avatar:'TM',text:'I’ll be there at 2pm. Please keep the geyser area clear.',timestamp:'10:42',unread:true}];
export function AppProvider({children}:{children:React.ReactNode}){const [role,setRoleState]=useState<Role>('customer');const [requests,setRequests]=useState<Request[]>(initialRequests);const [favourites,setFavourites]=useState<string[]>([]);const [messages,setMessages]=useState<Message[]>(defaultMessages);const [reviews,setReviews]=useState<Review[]>([]);const [providerStatuses,setProviderStatuses]=useState<Record<string,ProviderAccountStatus>>({p1:'approved',p2:'approved',p3:'approved',p4:'pending'});const [availability,setAvailabilityState]=useState<ProviderAvailability>({p1:true,p2:true,p3:true,p4:false});const [profile,setProfile]=useState<UserProfile>({name:'Alex Morgan',email:'alex@example.com',phone:'',address:'12 Long Street, Cape Town',notifications:true,role:'customer'});const [ready,setReady]=useState(false);useEffect(()=>{Promise.all([loadRequests(),loadFavourites(),loadMessages(),loadReviews(),loadProfile(),loadProviderStatuses(),loadAvailability()]).then(([r,f,m,v,p,ps,a])=>{if(r.length)setRequests(r);setFavourites(f);if(m.length)setMessages(m);setReviews(v);setProfile(p);setRoleState(p.role);setProviderStatuses(ps);setAvailabilityState(a);setReady(true);});},[]);useEffect(()=>{if(!ready)return;saveRequests(requests);saveFavourites(favourites);saveMessages(messages);saveReviews(reviews);saveProfile(profile);saveProviderStatuses(providerStatuses);saveAvailability(availability);},[requests,favourites,messages,reviews,profile,providerStatuses,availability,ready]);const setRole=(value:Role)=>{setRoleState(value);setProfile(p=>({...p,role:value}));};const value=useMemo<Context>(()=>({role,setRole,requests,addRequest:r=>setRequests(x=>[r,...x]),updateRequest:(id,status)=>setRequests(x=>x.map(r=>r.id===id?{...r,status}:r)),removeRequest:id=>setRequests(x=>x.filter(r=>r.id!==id)),favourites,toggleFavourite:id=>setFavourites(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]),messages,sendMessage:(providerId,text)=>setMessages(x=>{const existing=x.find(m=>m.providerId===providerId);if(existing)return x.map(m=>m.providerId===providerId?{...m,text,timestamp:'now',unread:false}:m);return [...x,{id:Date.now().toString(),providerId,provider:'FixMate pro',avatar:'FM',text,timestamp:'now',unread:false}];}),markMessageRead:id=>setMessages(x=>x.map(m=>m.id===id?{...m,unread:false}:m)),reviews,addReview:r=>setReviews(x=>[r,...x]),providerStatuses,setProviderStatus:(id,status)=>setProviderStatuses(x=>({...x,[id]:status})),availability,setAvailability:(id,value)=>setAvailabilityState(x=>({...x,[id]:value})),profile,updateProfile:patch=>setProfile(p=>({...p,...patch})),ready}),[role,requests,favourites,messages,reviews,providerStatuses,availability,profile,ready]);return <AppContext.Provider value={value}>{children}</AppContext.Provider>}
export const useApp=()=>useContext(AppContext);
